# template yaml config file
# rename to config.yaml to use
# requires a yaml module to be installed
# see http://pyyaml.org/

servers:
    crow2:
        address: localhost
        port: 6667
        nick: crow2
        user: crow
        realname: Crow2 IRC bot - http://github.com/lahwran/crow2
        channels:
            - '##crow2'